const fs = require("fs");
const dirname = require("path").dirname;
const path = require("path");

const metricsDir = dirname(require.resolve("@capsizecss/metrics/package.json"));
let filenames = fs.readdirSync(metricsDir);

const jsFiles = filenames.filter((filename) => filename.endsWith(".js"));

fs.writeFileSync(path.join(__dirname, "metrics.ts"), 
    `// This file is generated by generateMetrics.js
// It exports all metrics from @capsizecss/metrics as a single object
${jsFiles.map((filename) => `import ${filename.replace(".js", "")} from "@capsizecss/metrics/${filename.replace(".js", "")}";`).join("\n")}
    
export default {
    ${jsFiles.map((filename) => filename.replace(".js", "")).join(",\n    ")}
};
`);
